name = "UAG Units ACE3 Patch"
prefix = "UAG_Units_ACE3_Patch"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[properties]
author = "UAG Development Team"
url = "https://github.com/uagpmc/arma3"

[hemtt.launch.default]
workshop = [
    "2369477168", # Advanced Developer Tools Workshop ID
    "3263684880", # UAG Units
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]